### PR TITLE
added copy_flash_pages function

### PR DESCRIPTION
**Pull request by JAndrassy**
the makeall script doesn't use BIGBOOT for any board. some change of Makefile and makeall script must be made to include copy_flash_pages function in bootloader. simple would be replace SUPPORT_EEPROM with BIGBOOT and remove _eeprom_support postfix of the file name. Or you plan to add Tools menu options and I should use SUPPORT_COPY_PAGES and additional postfix to file name? How would you define the bootloader file name in boards.txt? name with _eeprom_support is not used now in boards.txt

### CODE REVIEW

**Comment by MCUdude** [comment]
Thanks for the PR. Could you please add some comments to the two functions you've added? For instance the do_smp function is very commented by majekw.

**Comment by JAndrassy** [comment]
comments added

**Comment by MCUdude** [comment]
Thanks! 

I was thinking about making this flash copy functionality enabled by default on 64kB+ AVRs. There's plenty of free space in the bootloader section (1024B is the smallest selectable bootloader space), so there's no need to save this space that cannot be used for anything else either.

A simple way is to wrap your code inside `#if FLASHEND > 0xfffe`

**Comment by JAndrassy** [comment]
it is now in BIGBOOT. BIGBOOT is set at default for all mcu with flash >= 64 kB., but can be set for smaller flash. copying the pages can be used on smaller flash. even for new version of application. only the sketch must be smaller then half of the flash. ArduinoOTA library does the transport over TCP and the libraries are large, but [the bin can be transferred over I2C for example](https://forum.arduino.cc/index.php?topic=586707) and then the application is smaller.

**Comment by JAndrassy** [comment]
I changed the PR here to use COPY_FLASH_PAGES_FNC command line option and define instead of BIGBOOT.
I made a PR to central Optiboot GitHub repo too

**Pull request closed without merging**
